name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # so Lerna can read tags

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.17.1
          registry-url: 'https://npm.pkg.github.com'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.13.1

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # - name: Bump versions via Lerna
      #   run: npx lerna version --conventional-commits --yes --no-push

      # - name: Push tags and release commit
      #   run: git push origin HEAD --follow-tags

      # - name: Publish changed packages
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      #   run: npx lerna publish from-package --yes
      
      - name: Publish changed packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx lerna publish --conventional-commits --yes
